import type { Metadata } from "next";
import { Heebo, Assistant } from "next/font/google";
import "./globals.css";

const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["hebrew", "latin"],
  weight: ["300", "400", "500", "700", "800", "900"],
});

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["hebrew", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import QueryProvider from "@/components/providers/QueryProvider";
import { WhatsAppButton } from "@/components/ui/WhatsAppButton";
import { getGlobalSettings } from "@/features/settings/actions";

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalSettings = await getGlobalSettings();

  return (
    <html
      lang="he"
      dir="rtl"
      data-scroll-behavior="smooth"
      className={`${heebo.variable} ${assistant.variable} h-full antialiased theme-${globalSettings.theme || "navy"}`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          {children}
          <WhatsAppButton 
            phoneNumber={globalSettings.contactPhone}
            defaultEmail={globalSettings.contactEmail}
            facebookUrl={globalSettings.contactFacebook}
            address={globalSettings.contactAddress}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
